import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import NavBar from "../../components/navbar"
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'],variable: '--font-inter',
display:'swap' })
const poppins = Poppins({
  weight: [ '400', '700'],
  subsets:['latin'],
  variable: '--font-poppins',
  display:'swap'
})

import { UiProvider } from "../../contexts/UiContext";
import Footer from '../../components/Footer';
export const metadata: Metadata = {
  title: 'Smart Recruiter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UiProvider>
      <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body suppressHydrationWarning={true} >
        <Toaster/>
        <NavBar />
        
        {children}
        <Footer/>
      </body>
        
      </html>
    </UiProvider>
  )
}
